### ISSUE TITLE
Verify the Visualizations

### ISSUE THREAD

**Issue by HimanshuRanka** [serotracker/Serotracker#39]
PENDING CHANGES

Check the title, content, legend, axis labels etc of all visualizations

**Comment by harrietware** [comment]
Amazing work! My comments:
Add WHO region and age group visualizations

Study count by pathogen & antibody type (ON DASHBOARD AND ANALYSIS):
1. Switch the x-axis and fill variables so that it's x-axis: pathogen and fill: antibody type
2. Change title to "Estimate count by arbovirus & antibody type"
3. Change yellow colour to something more legible on a white background (APPLIES TO ALL VIS)

Cumulative study count over time by pathogen (ON DASHBOARD AND ANALYSIS):
1. Change title to "Cumulative estimate count over time by arbovirus"

Cumulative study count over time by sample frame:
1. Remove "Figure X" from figure titles (APPLIES TO ALL VIS)
2. Change title to "Cumulative estimate count over time by sample frame"
3. Can we make the legend font smaller?
4. If possible, can we collapse the 3 smallest sample frames into an "Other" category?

Top ten countries with most studies by pathogen:
1. Change title to "Top ten countries reporting estimates by arbovirus"
2. Remove the country names from the y-axis label (keep in mouseover)
